name: nodejs-scripting-actions-workflow
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
      
permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          
      - run: npm install puppeteer
      
      - uses: actions/github-script@v8
        with:
          script: |
            const puppeteer = require('puppeteer');
            
            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.emulate(puppeteer.devices['iPhone 6']);
              await page.goto('https://www.nytimes.com/');
              await page.screenshot({path: 'full.png', fullPage: true});
              await browser.close();
            })();

      - uses: actions/upload-artifact@v5.0.0
        with:
          name: artifacts
          path: "full.png"
          
